version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongo
    ports:
      - "27019:27017" # Expose it on port 27019
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
